apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-poc
  namespace: poc-tekton
spec:
  params:
    - name: IMAGE_NAME
      default: quay.io/phatthananvst01/quaytekton
    - name: IMAGE_TAG
      default: v1.0.0

  workspaces:
    - name: shared-workspace

  tasks:
    - name: build-and-push
      taskRef:
        name: buildah        # ✅ Task ธรรมดา
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME):$(params.IMAGE_TAG)
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: shared-workspace
