apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-poc
  namespace: poc-tekton
spec:
  params:
    - name: GIT_URL
      type: string
      default: https://github.com/yforsine-afk/poc-tekton.git
    - name: GIT_REVISION
      type: string
      default: main
    - name: IMAGE
      type: string

  workspaces:
    - name: shared-workspace

  tasks:

    # ✅ STEP 1: Git Clone
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: shared-workspace

    # ✅ STEP 2: Build & Push (Kaniko)
    - name: build-and-push
      runAfter:
        - clone-repo
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace
