apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-and-push-run-
  namespace: poc-tekton
spec:
  serviceAccountName: pipeline

  pipelineRef:
    name: build-and-push-poc

  params:
    - name: IMAGE
      value: quay.io/phatthananvst01/quaytekton:v1.0.2

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
