apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-and-push-run-001
  namespace: poc-tekton
spec:
  pipelineRef:
    name: build-and-push-poc

  params:
    - name: IMAGE_NAME
      value: quay.io/phatthananvst01/quaytekton
    - name: IMAGE_TAG
      value: v1.0.0

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

  serviceAccountName: pipeline-sa
