apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
spec:
  description: Build and push container image using Kaniko
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      default: Dockerfile
    - name: CONTEXT
      default: .

  workspaces:
    - name: source

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      workingDir: $(workspaces.source.path)
      args:
        - "--dockerfile=$(params.DOCKERFILE)"
        - "--context=$(workspaces.source.path)/$(params.CONTEXT)"
        - "--destination=$(params.IMAGE)"
        - "--verbosity=info"
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
