apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
spec:
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
      default: Dockerfile
    - name: CONTEXT
      type: string
      default: .

  workspaces:
    - name: source

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      workingDir: $(workspaces.source.path)
      env:
        # ✅ วิธีเดียวที่ถูกต้องสำหรับ Kaniko v1.23.x
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      args:
      - --skip-push-permission-check
      - --push-ignore-immutable-tag-errors
      - --dockerfile=$(params.DOCKERFILE)
      - --context=$(workspaces.source.path)/$(params.CONTEXT)
      - --destination=$(params.IMAGE)
      - --verbosity=info

