apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko
  namespace: poc-tekton
spec:
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
      default: Dockerfile
    - name: CONTEXT
      type: string
      default: .
  workspaces:
    - name: source

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      workingDir: $(workspaces.source.path)
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      volumeMounts:
        - name: docker-config
          mountPath: /tekton/home/.docker
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(workspaces.shared-workspace.path)
        - --destination=$(params.IMAGE)
        - --verbosity=info
        - --skip-push-permission-check

  volumes:
    - name: docker-config
      secret:
        secretName: quay-secret

